name: User CI
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  ci_cd_common:
    uses: Sandeepkumar0088/reusable-github-actions/.github/workflows/ci-cd-direct-helm.yml@main
    with:
      component: user
      appType: nodejs